-- Query result:
-- For each item of the types
-- "STANDARD BURNISHED NICKEL", "ECONOMY ANODIZED STEEL" and "PROMO PLATED TIN",
-- output the supplier from Europe that has the lowest supply cost for the item.
-- The supply cost of an item is stored in the PartSupp table.
-- Arrange the result in descending order by
-- the partkey and ascending by the supplier's name.
--
-- Result scheme:
-- [PARTKEY (↓1) | SUPPLYCOST | SUPPLIER (↑2)]

SELECT PARTSUPP.PARTKEY AS PARTKEY,
       PARTSUPP.SUPPLYCOST,
       SUPPLIER.NAME AS SUPPLIER
FROM PARTSUPP
         JOIN PART ON PARTSUPP.PARTKEY = PART.PARTKEY
         JOIN SUPPLIER ON PARTSUPP.SUPPKEY = SUPPLIER.SUPPKEY
         JOIN NATION ON SUPPLIER.NATIONKEY = NATION.NATIONKEY
         JOIN REGION ON NATION.REGIONKEY = REGION.REGIONKEY
WHERE PART.TYPE IN ('STANDARD BURNISHED NICKEL', 'ECONOMY ANODIZED STEEL', 'PROMO PLATED TIN')
  AND REGION.NAME = 'EUROPE'
  AND PARTSUPP.SUPPLYCOST = (
    SELECT MIN(PS.SUPPLYCOST)
    FROM PARTSUPP PS
             JOIN SUPPLIER S ON PS.SUPPKEY = S.SUPPKEY
             JOIN NATION N ON S.NATIONKEY = N.NATIONKEY
             JOIN REGION R ON N.REGIONKEY = R.REGIONKEY
    WHERE PS.PARTKEY = PARTSUPP.PARTKEY
      AND R.NAME = 'EUROPE'
)
ORDER BY PARTSUPP.PARTKEY DESC, SUPPLIER.NAME ASC;


